### PR TITLE
Add individual get function for collections

### PR DESCRIPTION
**Pull request by KICKdesigns**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by wfg** [comment]
Let me know when you're ready to merge

**Comment by KICKdesigns** [comment]
Hi Wyatt,

I’ll generally only send PRs when files are ready to be merged, so you can go ahead and merge them as they come in. Thanks.

Best Regards,

- Jacqueline

Jacqueline Wang
Executive Director, KICKdesigns
jwang@KICKdesigns.com
415-737-5425 (415-737-KICK)

**Comment by wfg** [comment]
Understood. However, if I'd have merged instead of commenting originally, your second commit wouldn't have been included.

Merging now.

**Comment by KICKdesigns** [comment]
@wfg Thanks for the merge. Yes I know, I'll still ironing out the workflow. Some things can be tested locally and others can't and need the repo :)

**Pull request merged**
